version: '3'
services: 
  db: 
    image: mysql:custom
    container_name: appDB
    env_file: db.env
    networks: 
      - backend
    ports:
      - "3333:3306"
  app: 
    image: nodeapp
    restart: always
    container_name: app
    env_file: app.env
    ports: 
      - "3000:3000"  
    command: npm run start
    networks: 
      - backend 
    depends_on: 
      - db
  broker: 
    image: emqx/emqx:v3.2.8
    container_name: broker
    env_file: broker.env
    ports: 
      - "18083:18083"
    networks: 
      - backend
    depends_on: 
      - db 
networks: 
  backend: 